site_name: HEP ML Lab
repo_url: https://github.com/star9daisy/hep-ml-lab
repo_name: hep-ml-lab

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
  palette:
    primary: black
  icon:
    repo: fontawesome/brands/git-alt

plugins:
  - exclude:
      glob:
        - "**/data/*"
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
            members_order: source
            docstring_style: numpy
            separate_signature: true
            docstring_section_style: table
  - mkdocs-jupyter

markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Install:
      - pip: install/pip.md
      - Docker: install/docker.md
  - Getting started:
      - Generate events: getting_started/01_generate_events.md
      - Create datasets: getting_started/02_create_datasets.md
      - Apply approaches: getting_started/03_apply_approaches.md
  - User guides:
      - Observable naming conventions: user_guides/observable_naming_conventions.md
  - Code examples:
      - 1511.05190: code_examples/1511.05190.md
      - 1801.00797: code_examples/1801.00797.md
  - API reference:
      - hml.generators: api_reference/hml.generators.md
      - physics_objects:
          - single: api_reference/physics_objects/single.md
          - collective: api_reference/physics_objects/collective.md
          - nested: api_reference/physics_objects/nested.md
          - multiple: api_reference/physics_objects/multiple.md
      - hml.observables: api_reference/hml.observables.md
      - hml.representations: api_reference/hml.representations.md
      - hml.datasets: api_reference/hml.datasets.md
      - hml.approaches:
          - cuts: api_reference/hml.approaches/cuts.md
          - trees: api_reference/hml.approaches/trees.md
          - networks:
              - mlps: api_reference/hml.approaches/networks/mlps.md
      - hml.metrics: api_reference/hml.metrics.md
  - Release notes: release_notes.md
