site_name: HEP ML Lab
repo_url: https://github.com/star9daisy/hep-ml-lab
repo_name: hep-ml-lab


theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    primary: black
  icon:
    repo: fontawesome/brands/git-alt 

plugins:
  - exclude:
      glob:
        - examples/data/*
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
            members_order: source
            docstring_style: numpy
            separate_signature: true
            docstring_section_style: spacy

markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Getting started:
    - Installation: getting_started/installation.md
    - Quick start: getting_started/quick_start.md
  - Guides:
    - Generate events: guides/01_generate_events.md
    - Create datasets: guides/02_create_datasets.md
    - Apply approaches: guides/03_apply_approaches.md
  - Examples:
    - 1511.05190: examples/1511.05190.md
    - 1801.00797: examples/1801.00797.md
  - API:
      - hml.generators: api/hml.generators.md
      - hml.observables: api/hml.observables.md
      - hml.representations: api/hml.representations.md
      - hml.datasets: api/hml.datasets.md
      - hml.approaches:
          - cuts: api/hml.approaches/cuts.md
          - trees: api/hml.approaches/trees.md
          - networks:
              - mlps: api/hml.approaches/networks/mlps.md
      - hml.metrics: api/hml.metrics.md
      - hml.utils: api/hml.utils.md
  - History: history.md
