site_name: HEP ML Lab

theme:
  name: material
  features:
    - content.code.copy
  palette:
    primary: black

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
            members_order: source
            docstring_style: numpy
            separate_signature: true
            docstring_section_style: spacy

nav:
  - Introcution: index.md
  - API Reference:
      - hml.generators: api-reference/hml.generators.md
      - hml.datasets: api-reference/hml.datasets.md
