site_name: HEP ML Lab

theme:
  name: material
  features:
    - content.code.copy
  palette:
    primary: black

plugins:
  - exclude:
      glob:
        - examples/data/*
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
            members_order: source
            docstring_style: numpy
            separate_signature: true
            docstring_section_style: spacy

markdown_extensions:
  - toc:
      permalink: "#"

nav:
  - Introcution: index.md
  - Examples:
      - Generate events: examples/generate_events.ipynb
      - Create datasets: examples/create_datasets.ipynb
      - Apply methods: examples/apply_methods.ipynb
  - API Reference:
      - hml.generators: api-reference/hml.generators.md
      - hml.datasets: api-reference/hml.datasets.md
