site_name: HEP ML Lab

theme: readthedocs

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            members_order: source
            docstring_style: numpy
            separate_signature: true

nav:
  - Introcution: index.md
  - API Reference:
      - datasets: api-reference/datasets.md
      - generators: api-reference/generators.md
