site_name: HEP ML Lab

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
  palette:
    primary: black

plugins:
  - exclude:
      glob:
        - examples/data/*
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
            members_order: source
            docstring_style: numpy
            separate_signature: true
            docstring_section_style: spacy

markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Introcution: index.md
  - Examples:
      - Generate events: examples/generate_events.md
      - Create datasets: examples/create_datasets.md
      - Apply methods: examples/apply_methods.md
  - API Reference:
      - hml.generators: api-reference/hml.generators.md
      - hml.observables: api-reference/hml.observables.md
      - hml.representations: api-reference/hml.representations.md
      - hml.datasets: api-reference/hml.datasets.md
      - hml.preprocessing: api-reference/hml.preprocessing.md
      - hml.methods:
          - api-reference/hml.methods/cuts.md
          - api-reference/hml.methods/trees.md
          - Networks:
              - MLP: api-reference/hml.methods/networks/mlps.md
      - hml.metrics: api-reference/hml.metrics.md
