site_name: HEP ML Lab

theme: readthedocs

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            docstring_style: numpy

nav:
  - Introcution: index.md
  - API Reference:
      - datasets: api-reference/datasets.md
      - generators: api-reference/generators.md
