name: HML Tests

on:
  push:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    # container: star9daisy/hml-env:2.0.0

    steps:
    - uses: actions/checkout@v4

    - name: Check space
      run: df -h
    
    - name: Clean cache
      run: |
        rm -rf /opt/hostedtoolcache
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Check space again
      run: df -h
    
    - name: Run tests in Docker container
      uses: docker://star9daisy/hml-env:2.0.0
      with:
        args: bash -c "chmod +x /github/workspace/scripts/run_tests.sh && /github/workspace/scripts/run_tests.sh"
    
    # - name: Install Poetry
    #   run: |
    #     curl -sSL https://install.python-poetry.org | python3 -
    #     echo 'export PATH="/github/home/.local/bin:$PATH"' >> /github/home/.bashrc
    
    # - name: Install HML dependencies
    #   run: |
    #     export PATH="/github/home/.local/bin:$PATH"
    #     poetry install
    
    # - name: Run tests
    #   run: |
    #     export PATH="/github/home/.local/bin:$PATH"
    #     . /root/softwares/root6/bin/thisroot.sh
    #     export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/softwares/madgraph5/Delphes
    #     export ROOT_INCLUDE_PATH=/root/softwares/madgraph5/Delphes/external
    #     poetry run pip install keras --upgrade
    #     poetry run pip install torch==2.1.0 torchvision>=0.16.0 --extra-index-url https://download.pytorch.org/whl/cpu

    #     poetry run pytest -v --cov=hml --cov-report=xml tests
    #   shell: bash
    
    # - name: Upload coverage reports to Codecov
    #   uses: codecov/codecov-action@v3
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN}}
