name: HML Tests

on:
  push:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Clean cache
      run: rm -rf /opt/hostedtoolcache
    
    - name: Check space
      run: df -h